# Generated by Django 4.2.5 on 2023-09-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_school_dropout_data_drop_out_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolId', models.CharField(max_length=60)),
                ('principalId', models.CharField(max_length=60)),
                ('education_num', models.IntegerField(default=0)),
                ('economic_num', models.IntegerField(default=0)),
                ('medical_num', models.IntegerField(default=0)),
            ],
        ),
    ]
